package dataflue.cip.krule.entities;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Consumer Insight")
public class ConsumerInsight implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Offer Type")
   private java.lang.String offerType;
   @org.kie.api.definition.type.Label(value = "Offer Name")
   private java.lang.String offerName;
   @org.kie.api.definition.type.Label(value = "Offer Value")
   private java.lang.String offerValue;
   @org.kie.api.definition.type.Label(value = "Product Id")
   private java.util.List<java.lang.String> productId;
   @org.kie.api.definition.type.Label(value = "Threshold")
   private java.lang.String threshold;
   @org.kie.api.definition.type.Label(value = "Age")
   private java.lang.Integer age;

   public ConsumerInsight()
   {
   }

   public java.lang.String getOfferType()
   {
      return this.offerType;
   }

   public void setOfferType(java.lang.String offerType)
   {
      this.offerType = offerType;
   }

   public java.lang.String getOfferName()
   {
      return this.offerName;
   }

   public void setOfferName(java.lang.String offerName)
   {
      this.offerName = offerName;
   }

   public java.lang.String getOfferValue()
   {
      return this.offerValue;
   }

   public void setOfferValue(java.lang.String offerValue)
   {
      this.offerValue = offerValue;
   }

   public java.util.List<java.lang.String> getProductId()
   {
      return this.productId;
   }

   public void setProductId(java.util.List<java.lang.String> productId)
   {
      this.productId = productId;
   }

   public java.lang.String getThreshold()
   {
      return this.threshold;
   }

   public void setThreshold(java.lang.String threshold)
   {
      this.threshold = threshold;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public ConsumerInsight(java.lang.String offerType,
         java.lang.String offerName, java.lang.String offerValue,
         java.util.List<java.lang.String> productId,
         java.lang.String threshold, java.lang.Integer age)
   {
      this.offerType = offerType;
      this.offerName = offerName;
      this.offerValue = offerValue;
      this.productId = productId;
      this.threshold = threshold;
      this.age = age;
   }

}